### ISSUE TITLE
Should reportError log all errors to the console?

### ISSUE THREAD

**Issue by gshaw1997** [Cyber4All/learning-object-service#259]
As we continue to refactor error handling patterns in our services, many `console.log`/`console.error` statements are being removed and replaced with `reportError` in order to report errors to Sentry.

This makes debugging in production a breeze, but a pain in development as the reportError function only sends to Sentry while in production mode; makes sense.

As @nrwinner suggested, I think we should configure this function to log errors in development to the console using `console.error` which will ease debugging in development while keeping production logs clean and maintaining reporting in Sentry. Additionally, it gives us a single reporting mechanism for all internal service errors.

https://github.com/Cyber4All/learning-object-service/blob/f8b37915ff979ece973ba1aaefbbd953076eda0c/src/drivers/SentryConnector.ts#L1-L5

**Comment by DonSeannelly** [comment]
I think this makes sense. It's also a much better approach than putting console.error statements all over our code, as all unhandled errors should pass through this function.
