### ISSUE TITLE
Implement LearningObject level and metrics (likes and downloads)

### ISSUE THREAD

**Issue by ksherb1** [Cyber4All/learning-object-service#28]
When the LearningObject entity is adjusted to include an academic level. Schema needs to be adjusted.

`learning-object.schema.ts`

**Comment by tylernhoward** [comment]
Note, we will also need likes and metrics to complete cube's [issue 12](https://github.com/Cyber4All/cube/issues/12), stories 2 and 3

**Comment by DonSeannelly** [comment]
For the beta release, metrics will only include downloads. Issue #35 is a feature requests for implementing likes in the future.

**Comment by gshaw1997** [comment]
Injected AcademicLevel in https://github.com/Cyber4All/database-interaction/commit/a64292768143d2840e8ca41e84d0e1166081f1cd

**Comment by gshaw1997** [comment]
Duplicate. Closed in 100a7e0c19a642a9e1bb09fe472ad46eff6ce067
